<?php
return array(
	
	'title' 				=> 'Buat Toko Online',
	'title_second' 			=> 'Kelola Dari Genggaman',
	'title_description' 	=> 'Mulai dari Gratis!',
	'register_btn' 			=> 'Buat Toko',
	'register_description' 	=> 'Mulai buat Toko Online sekarang',
    'register_btn'          => 'Buat Toko',
	'register_term' 		=> 'Mendaftar berarti setuju dengan <a style="color: orange;" href="http://jarvis-store.com/kebijakan">kebijakan layanan</a>.',
	'video_btn' 			=> 'Lihat Video Perkenalan',
	'testimonial'			=> 'KATA KLIEN KAMI',
	'products_title' 		=> 'BEBERAPA BARANG POPULAR KLIEN KAMI',
	'cta_title' 		=> 'SUDAH SIAP PUNYA TOKO ONLINE SENDIRI ?',
	'cta_description' 		=> 'Daftar sekarang juga',
	'intro'             => array(
            'main_title'     => 'Toko Online Dengan Kebutuhanmu',
            'main_description'     => 'Kini kamu tak perlu repot lagi dalam membuat toko online. Dengan jasa pembuatan website toko online <strong>Jarvis Store</strong>, semua kebutuhan utama untuk <strong>toko online</strong> kamu tersedia disini. Karena kami selalu mendengar kebutuhan kamu. <i></i>',
            'main_h1'     => 'TOKO ONLINE PROFESIONAL',
            'main_h2'     => 'Jarvis Store memungkinkan anda memiliki toko online profesional seperti merek-merek terkenal dengan harga yang terjangkau.',
            'main_button'     => 'Tonton Video Perkenalan',
            'first_option'     => 'KELOLA DIMANAPUN',
            'first_desctiption'     => 'Jadilah penjual modern yang praktis, dinamis dan dikagumi yang mampu mengelola bisnis dari mana saja dan kapan saja.',
            'second_option'     => 'MUDAH DIGUNAKAN',
            'second_desctiption'     => 'Tidak perlu belajar lama untuk membuat dan mengelola toko online, platform Jarvis Store sangat mudah digunakan.',
            'second_btn'     => 'Video Tutorial',
            'second_lead'     => '* Sudah punya toko online? Tidak masalah, kita bantu migrasi dari toko online lama kamu ke Jarvis Store',
            'thrid_option'     => 'Fitur Lengkap',
            'thrid_desctiption'     => 'Semua fitur yang kamu butuhkan untuk berjualan online ada disini.',
            'thrid_btn'     => 'Lihat Semua Fitur',
            'feature_1'     => 'Diskon & Kupon',
            'feature_2'     => 'Pembayaran Lengkap',
            'feature_3'     => 'Integrasi Pengiriman',
            'fourth_option'     => 'GRATIS!',
            'fourth_desctiption'     => '<strong>Buat Toko Online Gratis</strong>, gratis <i>template</i> dan gratis <i>power up</i>. Gratis selamanya di Jarvis Store.',//'Selamanya! Ya, toko online kamu gratis selamanya.',
    ),
	'progress_setup' 		=> 'Toko anda sedang dibuat!',
);
