<?php
return array(
	
	'title' 			=> 'Data Pelanggan',
        'costumer'                      => 'Pelanggan',
        'member'                        => 'Member',
	'guest' 			=> 'Tamu',
	'message' 		=> 'Email kamu',
	'registered' 		=> 'Tanggal Masuk',
        'total_order'           => 'Total Order',
        'no_data'           => 'Belum ada data pelanggan di toko online Anda<br><a href="https://jarvis-store.com/artikel/10-cara-merilis-dan-mempromosikan-produk-melalui-social-media"><small>Pomosikan toko online Anda dan mulai dapatkan order dari pelanggan baru</small></a>',
	'create_btn' 		=> 'Tambah pelanggan baru',
	'breadcrumb' 	=> array(
                'main' => 'Pelanggan',
                'create' => 'Tambah baru',
                'edit' => 'Edit Pelanggan',
                'confirmation' => 'Konfirmasi Pembayaran',
	),
	'form_input' 			=> array(
                'first_title' => 'Data Umum',
                'data_order' => 'Data Order',
                'first_description' => 'Data standar umum pelanggan',
                'second_title' => 'Alamat',
                'second_description' => 'Alamat utama member / mitra',
                'third_title' => 'Data Lainnya',
                'third_description' => 'Data pelengkap member atau mitra',
                'name' => 'Nama Lengkap',
                'email' => 'Email',
                'costumer_type' => 'Tipe Pelanggan',
                'select_type' => 'Pilih Tipe',
        	        'member' => 'Member',
        	        'partner' => 'Mitra',
        	        'new' => 'Pelanggan Baru',
                'password' => 'Password',
                're_password' => 'Ulang Password',
                'post_code' => 'Kode Pos',
                'company' => 'Perusahaan',
                'phone' => 'Telepon',
                'address' => 'Alamat',
                'country' => 'Negara',
                'state' => 'Provinsi',
                'city' => 'Kota',
                'dob' => 'Tanggal Lahir',
                'note' => 'Catatan Khusus',
                'tags' => 'Tags',
                'be_member' => 'Terdaftar sebagai member',
                'be_partner' => 'Terdaftar sebagai Mitra',
                'be_guest' => 'Order sebagai Tamu',
	),
        'profile'    => array(
                'title' => 'Profile Admin',
                'first_title' => 'Data Umum',
                'first_description' => 'Data standar Umum administrator',
                'second_title' => 'Alamat',
                'second_description' => 'Alamat utama administrator',
                'third_title' => 'Data Lainnya',
                'third_description' => 'Data pelengkap informasi',
        ),
	'forget_password' 	=> 'Lupa Password',
	'forget_button' 		=> 'Klik disini untuk mengganti password',
	'remember' 			=> 'Ingat email dan password',
	'login_button' 		=> 'Masuk'

);
