<?php
return array(
	
	'month_stat' 			=> 'Statistik Bulanan',
	'visit' 			=> 'Visits',
	'pageview' 	=> 'Pageviews',
	'visitor' 			=> 'Visitors',
	'new_visitor' 	=> 'New Visitors',
	'welcome' 		=> 'Selamat Datang di Dashboard Toko Anda',
	'welcome_info' 			=> 'sedikit langkah lagi untuk memulai berjualan dengan toko online anda',
	'step1' 		=> '1. Cara Masukkan Produk',
	'step1_info' 		=> 'Klik gambar di atas untuk melihat cara memasukkan produk yang ingin anda jual di toko online anda dari menu Katalog',
	'step1_button' 		=> 'Masukkan Produk',
	'step2' 		=> '2. Cara mengubah Tampilan',
	'step2_info' 		=> 'Klik gambar di atas untuk melihat cara memasukan gambar logo toko, slideshow, dan banner promo dari menu Tema',
	'step2_button' 		=> 'Update Tampilan',
	'step3' 		=> '3. Cara Setting Pembayaran',
	'step3_info' 		=> 'Klik gambar di atas untuk melihat cara mengatur pembayaran yang digunakan, seperti transfer bank, dan pembayaran lainnya dari menu Pembayaran',
	'step3_button' 		=> 'Setting Pembayaran',
	'step4' 		=> 'Launching Toko',
	'step4_info' 		=> 'Toko online anda sudah siap untuk berjualan dan menerima order dari seluruh penjuru dunia',
	'step4_button' 		=> 'Lihat Toko',
	'finish' 		=> 'SELESAI',
	'quick_navigation' 		=> 'Navigasi Cepat',
		'costumer' 		=> 'Pelanggan',
		'orders' 		=> 'Order',
		'product' 		=> 'Produk',
		'statistic' 		=> 'Statistik',
		'report' 		=> 'Laporan',
		'testimonial' 		=> 'Testimonial',
		'add_order' 		=> '+ Order',
		'add_category' 		=> '+ Kategori',
		'add_product' 		=> '+ Produk',
		'add_discount' 		=> '+ Diskon',
		'add_costumer' 		=> '+ Member',
		'add_blog' 		=> '+ Blog',
		'themes' 		=> 'Tema',
		'setting' 		=> 'Pengaturan',
	'new_order' 		=> 'Order Baru',
	'order_id' 		=> 'Kode Order',
	'name' 		=> 'Nama Pelanggan',
	'date' 		=> 'Tanggal',
	'total' 		=> 'Total',
	'status' 		=> 'Status',
		'pending' 		=> 'Pending',
		'confirmation' 		=> 'Konfirmasi diterima',
		'paid' 		=> 'Pembayaran diterima',
		'send' 		=> 'Terkirim',
		'cancel' 		=> 'Batal',
	'no_order' 		=> 'Order hari ini masih kosong...',
	'help'    => array(
                'step1' => 'Urutan kategori produk, klik dan drag untuk mengatur posisi kategori',
                'step2' => 'Klik untuk update kategori yang dipilih',
                'step3' => 'Klik untuk menghapus kategori yang dipilih',
                'step4' => 'Klik untuk menambah kategori baru',
                'step5' => 'Ini button untuk melakukan pengaturan produk',
                'step6' => 'Ini button untuk melakukan pengaturan produk',
                'step7' => 'klik disini untuk menghapus produk yang telah di pilih',
                'step8' => 'klik disini untuk memasukan produk baru',
        ),

);
