<?php
return array(
        
        'title'                 => 'Data Diskon',
        'list'                 => 'List Diskon',
        'all_data'                 => 'Semua Diskon',
        'breadcrumb'    => array(
                'main' => 'Diskon',
                'create' => 'Tambah Diskon Baru',
                'edit' => 'Edit Diskon',
        ),
        'details'                 => 'Rincian Diskon',
        'active'                 => 'Aktif',
        'nonactive'                 => 'Non Aktif',
        'expired'                 => 'Expired',
        'qty'                 => 'Jumlah',
        'start'                 => 'Mulai',
        'finish'                 => 'Berakhir',
        'form_input'  => array(
                'first_title' => 'Data Diskon',
                'first_description' => 'Data standar Diskon',
                'second_title' => 'Data Produk',
                'second_description' => 'Tambahkan produk ke dalam Diskon',
                'code' => 'Kode',
                'generate' => 'Kode Acak',
                'type' => 'Jenis Potongan',
                'nominal' => 'Nominal',
                'percent' => 'Persen',
                'discount' => 'Besar Potongan',
                'minimal' => 'Minimal Nominal Total Belanja',
                'minimal_warning' => '* Untuk menghidari kesalahan hitung, minimal belanja harus sama atau lebih dari diskon yang diberikan.',
                'start' => 'Tanggal Mulai',
                'finish' => 'Tanggal Berakhir',
                'maximum' => 'Jumlah maksimum penggunaan kupon',
                'used' => 'Jumlah kupon yang sudah digunakan',
                'product' => 'Per Produk  ',
                'category' => 'Per Kategori  ',
                'collection' => 'Per Koleksi  ',
                'no_product' => 'Tidak ada produk',
                'all_product' => 'Semua Produk',
                'all_category' => 'Semua Kategori',
                'all_collection' => 'Semua Koleksi',
                'select_category' => 'Pilih Kategori',
                'select_collection' => 'Pilih Koleksi',
                'second_title' => 'Data Produk yang di diskon',
                'secont_description' => 'Data pilihan produk, kategori produk atau koleksi produk yang dimasukan diskon',
        ),
        'no_data'       => 'Belum ada data Diskon',
        'until'       => 'sampai',
        'text_until'       => 'kupon digunakan dari jumlah keseluruhan kupon',
        'product'       => 'Product',
        'category'       => 'Category',
        'collection'       => 'Collection'

);
