<?php
return array(
	
	'title' 		=> 'Daftar Order',
	'all_order' 		=> 'Semua',
	'day_order' 		=> 'Hari ini',
	'month_order' 		=> 'Bulan ini',
	'no_data' 		=> 'Belum ada data order di toko online Anda',
	'delete_btn' 	=> 'Hapus',
	'create_btn' 	=> 'Buat Order Baru',
	'order_code' 	=> 'Kode Order',
	'costumer_name' 	=> 'Nama Pelanggan',
	'date' 	=> 'Tanggal',
	'total' 	=> 'Jumlah',
	'paid' 	=> 'Dibayar',
	'create' => array(
        'title' => 'Data Order Baru',
		'create_btn' => 'Buat order',
		'summary' => 'Ringkasan Order',
		'costumer' => '1. Pilih pelanggan',
			'buyer' => 'Pembeli',
			'receiver' => 'Penerima',
		'cart' => '2. Tambah Produk ke keranjang',
			'total_order' => 'Total Belanja',
		'expedition' => '3. Pilih Kurir Pengiriman',
			'free_ship' => 'Free Shipping',
		'costumer_data' => 'Data Pelanggan',
			'costumer_data_same' => 'Data Penerima sama dengan data pelanggan',
			'receipt_data' => 'Data Penerima',
		'product_data' => 'Data Produk',
			'product_name' => 'Kode Produk / Nama',
			'select_product' => 'Pilih Produk',
			'variant' => 'Varian / Opsi',
			'select_option' => 'Tidak ada Option/Varian',
			'quantity' => 'Jumlah',
			'add' => 'Tambahkan',
			'open_cart' => 'Keranjang Belanja',
			'empty_cart' => 'Keranjang belanja masih kosong.',
			'total' => 'Total',
			'discount_kode' => 'Kode Diskon',
			'use_discount' => 'Pakai Kode Diskon',
			'no_discount' => 'tidak ada potongan',
			'shipping' => 'Ongkos Kirim',
			'tax' => 'Pajak',
			'uniq_code' => 'Kode Unik',
			'total_buy' => 'Total',
		'expedisi_data' => 'Data Penerima',
			'city_to' => 'Masukan Kota Tujuan',
			'select_shipping' => 'Pilih Ekspedisi',
			'result_shipping' => 'Shipping from',
			'search' => 'Cari',
	),
	'edit' => array(
        'title' => 'Data order',
        'status' => 'Status order',
        'edit_status' => 'Ubah status',
        'expedition_no' => 'No pengiriman (Resi)',
        'confirmation' => 'Konfirmasi pembayaran',
        'no' => 'No.',
        'subtotal' => 'Subtotal',
        'deliveryId' => 'Isi dengan <strong>0000</strong> jika resi tidak tersedia',
        'messege' => '<h4 class="alert-heading">Maaf!</h4> Order ini belum memiliki konfirmasi pembayaran.',
        'update_btn' => 'Update Order',
        'shipping_btn' => 'Kirim Resi ke Pelanggan',
        'note' => 'Pesan',
        'from' => "Dari",
        'to' => "Kepada",
        'recipient' => "Nama penerima",
        'shipping' => 'Nama ekspedisi',
        'shippingId' => 'No resi',
		'total_tranfer' => 'Total',
		'transfer_date' => "Tanggal transfer",
        'account_id' => 'Rekening pengirim',
        'account_to' => 'Rekening tujuan',
		'total_tranfer' => 'Total',
		'print_invoice' => 'Cetak invoice',
		'print_shipping' => 'Cetak pengiriman',
	),
	'status' => array(
        'status' => 'Status ',
        'pending' => 'Pending',
        'confirm' => 'Konfirmasi diterima ',
        'pay' => 'Pembayaran diterima',
        'sent' => 'Terkirim',
        'cancel' => 'Batal',
        'transfer' => 'Transfer',
        'confirmation' => 'Konfirmasi',
        'unpaid' => 'Belum',
        'no_costumer' => 'Data Pelanggan ini telah terhapus'
	),
	'notification' => [
		'search_expedition' => [
			'title'	=> 'Pemberitahuan!',
			'text'	=> 'Mohon tunggu sebentar, sistem sedang mencari list ekspedisi ke kota tujuan kamu.'
		]
	]


);
