<?php
return array(
	
	'header' => array(
                    'tour' => 'Tour',
					'help' => 'Bantuan & Tips',
					'system_overview' => 'Kapasitas Toko',
					'disk_usage' => 'Kapasitas Penyimpanan',
					'product_quota' => 'Kuota Produk',
					'goto_shop' => 'Lihat Toko',
					'profile' => 'Profil',
					'account_billing' => 'Akun & Tagihan',
					'logout' => 'Logout'
				),
	'helper' => array(
                    'title' => 'Butuh Bantuan ?',
					'tutorial' => 'Tutorial',
					'video' => 'Video',
					'report_email' => 'Lapor',
					'report_deskription' => 'Laporan (bug, error, saran, dan masukan)',
					'live_chat' => 'Tanya',
					'cancel' => 'Batal',
				),
	'menu' => array(

					'dashboard' => 'Dashboard',
					'order' => 'Order',
					'costumer' => 'Pelanggan',
					'catalog' => 'Katalog',
					'category' => 'Kategori',
					'product' => 'Produk',
					'collection' => 'Koleksi',
					'discount' => 'Diskon',
					'expedition' => 'Ekspedisi',
					'write' => 'Tulisan',
					'blog' => 'Blog',
					'pages' => 'Halaman',
					'link' => 'Tautan',
					'testimonial' => 'Testimonial',
					'report' => 'Laporan',
					'statistic' => 'Statistik',
					'power_up' => 'Power up',
					'themes' => 'Tema',
					'payment' => 'Pembayaran',
					'setting' => 'Pengaturan',

				),
	'message' => array(
                    'free_pack' => 'Toko anda menggunakan paket Free',
					'info_pack' => 'Informasi Paket, Silakan Cek Disini',
					'upgrade_pack' => 'Untuk meng-upgade Paket, Silakan Cek Disini',
					'trial_pack' => 'Upgrade paket untuk menikmati fitur lengkap',
					'reminder_pack' => 'Paket anda telah berakhir, toko anda hanya dapat menampilkan 10 produk',
					'link_reminder_pack' => 'Segera perpanjang paket toko online anda disini',
					'notification' => 'Pada pukul 21:00 sampai dengan pukul 24:00 WIB akan dilakukan maintenance sehingga beberapa fitur tidak dapat digunakan pada jeda waktu tersebut. <a target="Blank_" href="https://jarvis-store.com/artikel/jadwal-maintenance-september">selengkapnya..</a>',
					'verify1' => '<h4>Pemberitahuan!</h4>Halo, akun kamu belum melewati tahap verikasi email untuk menandakan akun kamu valid.
				  Silakan buka inbox/spam dari email',
					'verify2' => 'dan verifikasi akun kamu dengan mengklik link yang kami kirim ke email kamu.',
					'resend' => 'Kirim ulang email verifikasi!',
        			'reminder_msg'  => 'Paket Anda akan segera berakhir dalam :obj hari lagi. Untuk terus dapat menikmati fitur-fitur kami, segara lakukan pembayaran paket jarvis kamu, atau hubungi kami <a id="247" class="blue"><strong>disini</strong></a> untuk bantuan. <br><br><a id="hide_notif" class="pull-right" style="cursor:pointer"><em>(Jangan Tampilkan)</em></a>',
        			'notification'  => 'Pemberitahuan!',
				),
	'button' => array(
                    'create' => '<i class="fa-icon-plus"></i> <span class="hidden-phone hidden-tablet"> Tambah</span>',
					'delete' => '<i class="fa-icon-trash"></i> <span class="hidden-phone hidden-tablet"> Hapus</span>',
					'save' => 'Simpan',
					'export' => 'Export',
					'import' => 'Import',
					'reset' => 'Reset',
					'creating' => 'Tambahkan',
					'cancel' => 'Batal',
					'download' => 'Download',
					'send' => '<i class="fa-icon-envelope"></i> <span class="hidden-phone hidden-tablet"> Kirim</span>',
					'see_tutorial' => 'Lihat Tutorial'
				),
	'report' => array(
        'repoty' => 'Laporan',
        'product' => 'Laporan Produk',
        	'views' => 'Views ',
	        'sold' => 'Sell ',
	        'top_sell' => 'TOP 10 Produk Paling Laku',
	        'top_view' => 'TOP 10 Produk Dilihat',
        'order' => 'Laporan Order',
	        'order_total' => 'Total Orders',
	        'order_status' => 'Orders Status',
	        'top_city' => 'TOP 5 Pemesanan',
	        'top_costumer' => 'TOP 10 Order Pelanggan',
	        'top_shipping' => 'TOP 5 Pengiriman',
	        'no_costumer' => '<small>Pelanggan telah dihapus</small>',
        'payment' => 'Laporan Pembayaran',
        	'payment_method' => 'Pembayaran',
        	'top_payment' => 'Metode Pembayaran Terpopuler',
        'statistic' => 'Laporan Statistik Web',
        'finance' => 'Laporan Keuangan',
	),
);
