<?php
return array(
	'menu' => array(
                    'general' => 'General',
					'payment' => 'Pembayaran',
					'account' => 'Akun & Billing',
					'tax' => 'Pajak',
					'admin' => 'Administrator',
					'notif' => 'Notifikasi',
					'file' => 'Pengaturan File',
					'domain' => 'Domain',
					'info' => 'Info Update',
				),

	'index' => array(
                    'title' => 'Tema yang Aktif',
					'desc' => 'Pengaturan tentang toko online untuk optimasi SEO',
					'view_theme_store' => 'Lihat Theme Store &rarr;',
					'active_theme' => 'TEMA AKTIF',
					'btn_update_theme' => 'Update Tema',
					'info_theme' => 'update info?',
					'info_update' => 'Last Update',
					
					'btn_theme_apperance' => 'Atur Tampilan',
					'btn_theme_html' => 'Edit HTML/CSS',
					'btn_theme_reset' => 'Reset Tema',

					'no_template' => 'Belum ada template yang aktif<br><small>Silahkan aktifkan tema yang tersedia dibawah ini.</small>',
					'avaiable_theme' => 'Tema Saya',
					'btn_activated' => 'Aktif',
					'btn_buy_template' => 'Beli Tema',
					'btn_activation' => 'Aktifkan',
					'btn_delete_theme' => 'Hapus',

					'other_theme' => 'Tema Lainnya',
					'bnt_install' => 'Pasang',
					'btn_demo' => 'Demo',
					'btn_view_theme_store' => 'Tema Lainnya &rarr;',
					'tutorial_1' => 'Klik di sini untuk mengatur tampilan website seperti Gambar Logo, Gambar Slideshow dan Gambar Banner',

				),
	
	'setting' => array(
                    'title' => 'Pengaturan Tampilan Tema',
					'back' => 'Tema',

					'color' => array(
	                    'title' => 'Warna',
	                    'title2' => 'Pengaturan Warna Tema',
						'not_avaiable' => 'Perubahan Warna tidak tersedia di Tema ini.',
						'reset' => 'Reset Warna',
						'info' => 'Kustomisasi warna berbeda-beda tergantung pada tema yang dipilih. Tidak semua tema memiliki pengaturan kustomisasi warna',
						'theme_color' => 'Warna Tema'
					),
					'logo' => array(
	                    'title' => 'Gambar Logo',
	                    'title2' => 'Gambar Logo Toko',
						'info_logo' => 'Silakan upload gambar logo dengan format/extensi <strong>JPG</strong> atau <strong>PNG</strong> kemudian gunakan ukuran tinggi maksimal : <strong>150 pixels</strong> dan lebar akan menyesuaikan dengan tema yang digunakan.',
						'upload_logo' => 'upload logo ? klik tombol berikut untuk upload',
						'btn_update_logo' => 'Update Logo',
						'title3' => 'Favicon Website',
						'info_favicon' => 'Silakan upload logo favicon dengan format/extensi <strong>JPG</strong> atau <strong>PNG</strong> dan pastikan gunakan ukuran : <strong>75 x 75 pixels</strong>.',
						'upload_favicon' => 'upload favicon ? klik tombol berikut untuk upload',
						'btn_update_favicon' => 'Update Favicon',
					),
					'slide_show' => array(
	                    'title' => 'Gambar Slideshow',
	                    'title2' => 'Gambar Slideshow Halaman Utama',
						'info_slideshow' => 'Silakan upload gambar Slideshow dengan format/extensi <strong>JPG</strong> atau <strong>PNG</strong> dan pastikan gunakan ukuran : <strong>940 x 400 pixels</strong> untuk tampilan terbaik.',
						'slideshow' => 'Gambar Slideshow',
						'add_slideshow' => ' Tambah Slideshow',
						'upload_slideshow' => 'Mau ubah gambar slide? klik tombol berikut untuk upload',
					),
					'banner' => array(
	                    'title' => 'Gambar Banner',
	                    'title2' => 'Atur Gambar Banner',
	                    'title3' => 'Side Banner (250x400)',
	                    'title4' => 'Main Banner (980x200)',
						'info_sidebanner' => 'Silakan upload Sidebar Banner dengan format/extensi <strong>JPG</strong> atau <strong>PNG</strong> dan pastikan gunakan ukuran : <strong>250 x 400 pixels</strong>.',
						'info_mainbanner' => 'Silakan upload Mainbar Banner dengan format/extensi <strong>JPG</strong> atau <strong>PNG</strong> dan pastikan gunakan ukuran : <strong>980 x 200 pixels</strong>.',
						'btn_add_banner' => 'Tambah Banner Baru',
						'input_url' => 'Banner Link / URL tujuan',
						'placeholder_input_url' => 'url banner saat diklik ',
						'input_image' => 'Ganti Gambar',
						'btn_delete' => 'Hapus',
						'type_banner' => 'Tipe Banner',
						'select_type_banner' => '-- Pilih Tipe Banner --',
						'main_banner' => 'Untuk hasil terbaik, ukuran mainbar banner : 980x200 pixel',
						'side_banner' => 'Untuk hasil terbaik, ukuran sidebar banner : 250x400 pixel',
					),
					'sosial_media' => array(
	                    'title' => 'Sosial Media',
	                 ),
					'mailing_list' => array(
	                    'title' => 'Mailing List',
						'info_mail' => 'Tidak semua tema mendukung fitur milis / email newsletter',
						'mailchimp_url' => 'Mailchimp Form Action URL<br><small>Daftar di <a target="_blank" href="http://mailchimp.com/">mailchimp.com</a></small>',
						'mailchimp_tagline' => 'Mailing List Tagline',
						'mailchimp_title' => 'Mailing List Title',
					),
					'product' => array(
	                    'title' => 'Jumlah Tampilan Item',
	                    'title2' => 'Atur jumlah item yang di tampilkan',
						'no_product' => 'Tema ini tidak dapat untuk mengatur jumlah produk',
						'home' => 'Halaman Utama',
						'main' => 'Halaman Produk',
						'related' => 'Produk Lainnya',
						'lastest' => 'Produk Terbaru',
						'bestseller' => 'Bestseller',
						'featured' => 'Featured',
						'blog' => 'Halaman Blog',
						'testimonial' => 'Testimonial',
						'image' => 'Gambar Produk',
						'slideshow_width' => 'Lebar Slideshow',
						'mainbanner_width' => 'Lebar Mainbanner',
						'sidebanner_width' => 'Lebar Sidebanner',
					),
					'layout' => array(
	                    'title' => 'Layout Halaman Depan',
	                    'title2' => 'Atur Layout Halaman Depan',
						'info_slideshow' => 'Untuk layout sidebar dikanan atau dikiri mengikuti desain tema. Tidak semua desain tema memiliki pilihan untuk mengatur layout.',
						'select_layout' => 'Pilih Layout Homepage',
						'default_layout' => 'Layout Default',
					),
					'maintenance' => array(
	                    'title' => 'Halaman Maintenance',
	                    'title2' => 'Atur Tampilan Maintenance',
						'active' => 'Aktifkan Halaman Website',
						'non_active' => 'Non Aktifkan Halaman Maintenance',
						'upload_slideshow' => 'Mau ubah gambar slide? klik tombol berikut untuk upload',
					),
				),
	'account' => array(
                    'msg_fail' => 'Kami mengalami kesalahan sebagai berikut:',
					'msg_success' => 'Update berhasil di lakukan..',
					'msg_fail_billing' => 'Maaf, Billing anda tidak berhasil dikirim..',
					'msg_success_billing' => 'Terima Kasih, Billing anda telah dikirimkan..',
					'msg_fail_konfirm' => 'Maaf, Konfirmasi billing anda gagal..',
					'msg_success_konfirm' => 'Terima Kasih, Billing anda sudah berhasil dikonfirmasi..',
					'title' => 'Tentang Akun',
					'desc' => 'Rangkuman tentang akun anda',
					'register_date' => 'Terdaftar Tanggal',
					'owner' => 'Account Owner',
					'close_account' => 'Tutup Toko Jarvis Store',
					'billing' => 'Tagihan Perpanjangan Selanjutnya',
					'free_forever' => 'Gratis Selamanya',
					'trial' => 'Full Trial sampai',
					'active_to' => 'aktif sampai',
					'title_2' => 'Billing Info',
					'desc_2' => 'Tentang data penagihan untuk perpanjangan penggunaan sistem',
					'will_expire' => 'Masa trial anda segera habis? Tenang saja, silakan pilih salah satu paket dibawah ini dan mulai berjualan.',
					'expired' => 'Opps, Trial anda sudah habis? Yuk pilih paket kita yang lain dan dapatkan semua fitur Jarvis Store.',
					'upgrade' => 'Mau upgrade paket? Tenang saja, silakan pilih salah satu paket dibawah ini.',
					'download' => 'Tentang data penagihan untuk perpanjangan penggunaan sistem',
					'active' => 'Aktif',
					'order_now' => 'Pesan Sekarang!',
					'title_3' => 'Member & Affiliate',
					'desc_3' => 'Halaman member Jarvis Store & Afiliasi',
					'go_to_aff' => 'Menuju ke halaman member & Afiliasi Jarvis Store',
					'title_4' => 'Tutup Akun dan Toko di Jarvis Store',
					'desc_4' => 'Menutup Akun akan membuat toko anda tidak dapat di akses, menonaktifkan semua fitur dan menghapus semua data (laporan, gambar, database) yang ada ditoko anda.',
					'reason' => 'Reason',
					'option1' => 'Have a other Account',
					'option2' => "Don't understand to use Jarvis Store",
					'info_option2' => 'Please check Help Button on top of your dashboard or you can <a style="cursor: pointer;" id="bantuan1"><strong>click here</strong>',
					'option3' => 'Others',
					'info_option3' => 'explaination..',
					'disable' => 'Unsubscribe Notification (Reminder and Update) to my email',
				),
	'notification' => array(
                    'title' => 'Template Email',
					'desc' => 'Template email manager, you must to understand <b>Blade System Template</b> for edit your email template.',
					'desc2' => 'Please tell us to <a href="mailto:support@jarvis-store.com">support@jarvis-store.com</a> for help edit your email template.',
					'subject' => 'Subject Email',
					'content' => 'Content:',
					'title_2' => 'Email Admin',
					'desc_2' => 'Administrator Email that will get notification',
					'email' => 'Email Admin',
				),
	'domain' => array(
                    'title' => 'Domain Manager',
					'desc' => 'Manage your Jarvis Store domain and your own domain',
					'domain_jarvis' => 'Jarvis Store Domain',
					'upgrade' => 'Want to use my own domain? Please upgrade your Jarvis Store Pack in Menu <b>Setting</b> > <b>Account</b> ',
					'order' => "create new domain ? Please order here",
					'parking' => 'Have domain ? You can park your domain below !',
				),
	'info' => array(
                    'title' => 'Information',
					'desc' => 'Please fell free to contact us if you need Information and Update to <a href="mailto:info@jarvis-store.com">info@jarvis-store.com</a> or check our <a href="http://jarvis-store.com/artikel">Blogs</a>.',
					'aff_jarvis' => 'Now Jarvis Store has affiliate program for you. Get addtional income by tell your friend or your partner to using Jarvis Store. For details information please check in this (link to : <a href="http://jarvis-store.com/partner/afiliasi" target="_blank">http://jarvis-store.com/partner/afiliasi</a> )',
				),
	'administrator' => array(
                    'breadcrumb_1' => 'Setting',
                    'breadcrumb_2' => 'Administrators',
					'breadcrumb_3' => 'List of Administrator',
					'breadcrumb_4' => 'Edit Administrator',
					'breadcrumb_5' => 'Add a new Administrator',

					'data_admin' => 'Data Administrator',
					'data_general' => 'General',
					'data_standard' => 'Standard Data for Administrator',
					'data_contact' => 'Data Contact',
					'data_info_contact' => 'Contact Information',
					'data_other' => 'Other Data',
					'data_addtional' => 'Addtional Data',

					'authorization' => 'Authorization',
					'author_full' => 'Full Access',
					'author_catalog' => 'Access for Product, Product Categories, Collection',
					'author_content' => 'Access for Pages, Blogs, Links, Testimonials',
					'author_sales' => 'Access for Orders, Costumers, dan Discount',

					'nama' => 'Name',
					'email' => 'Email',
					'phone' => 'Phone Number',
					'login' => 'Last Log in',
					'action' => 'Action',

				),
);
