<?php

return array(

	'title' 	=> 'Rincian Belanja',
	'description' 	=> 'Website kami akan segera hadir. Untuk informasi lebih lanjut silakan hubungi kami di.',
	'empty_cart'	=> "<h1>Keranjang Belanja Masih Kosong.</h1><p>Silahkan masukan produk ke keranjang belanja</p><br> <a class='btn btn-primary' href='../produk'>Lihat koleksi produk kami</a>.",
	'address'	=> "Alamat",
	'img' => 'Gambar',
	'product' => 'Produk',
	'qty' => 'Jumlah',
	'price' => 'Harga',
	'subtotal' => 'Subtotal',
	'shipping' => 'Ongkos Kirim',
	'free_ship' => 'Pengiriman Gratis',
	'next_ship' => 'Pengiriman Menyusul',
	'discount' => 'Potongan/Diskon',
	'tax' => 'Pajak',
	'tax_active' => 'Active',
	'tax_nonactive' => 'Non Active',
	'code' => 'Kode Unik',
	'totals' => 'Total Keseluruhan',
	'coupons' => 'Punya Kupon ?',
	'input_coupons' => 'Masukan kode kupon anda',
	'place_coupons' => 'Kode kupon...',
	'use_coupons' => 'Pakai Kupon',
	'cancel' => 'Batal',
	'shipping_cost' => 'Biaya Pengiriman',
	'des_destination' => 'Masukkan kota tujuan anda untuk menghitung biaya pengiriman',
	'cancel' => 'Batal',
	'search' => 'Cari',
	'city_not_found' => 'Bila kota anda tidak ditemukan atau tidak ada dalam daftar, pilihlah kota yang terdekat atau <a href="../kontak">hubungi kami</a>.',
	'free_ship_des' => 'Anda tidak dikenakan biaya pengirimiman pada order ini.',
	'login' => 'Lanjut sebagai ?',
	'login_des' => 'Login sebagai member untuk mempercepat order ini',
	'forget_password' => 'Lupa Password?',
	'new_member' => 'Pelanggan Baru ? <a href="../member/create">klik disini.</a>',
	'reg_member_des' => 'Lanjut sebagai Member',
	'new_member_des' => 'Pilih tombol dibawah untuk melanjutkan order!',
	'view_other' => 'Lihat Produk Lainnya',
	'back' => 'Kembali',
	'continue_as_guest' => 'Lanjut sebagai Tamu',
	'or_register_member' => 'atau',
	'register_member' => 'Pelanggan Baru ?',
	'continue' => 'Lanjutkan',

);
